import re

PROVIDER_RULES: list[tuple[str, list[str]]] = [
    ("OpenAI", [r"\b(?:chatgpt|gpt(?:[-\s]oss)?)\b"]),
    ("Teknium", [r"\bopenhermes[0-9a-z_-]*\b"]),
    ("Nous Research", [r"\b(?:nous(?:[-\s]hermes)?|hermes[0-9a-z_-]|yarn[0-9a-z._-])\b"]),
    ("Alibaba", [r"\b(?:qwen\d+|qwen|qwq|tongyi|codeqwen[0-9a-z_-]*)\b"]),
    ("Deep Cogito", [r"\bcogito\b"]),
    ("Perplexity", [r"\br1[-\s]1776\b"]),
    ("DeepSE", [r"\bcodeup\b"]),
    ("DeepSeek", [r"\bdeepseek\b"]),
    ("Google", [r"\b(?:gemini|palm|[a-z]*gemma[0-9a-z_-]*)\b"]),
    ("IBM", [r"\bgranite[0-9a-z_-]\b"]),
    ("LightOn", [r"\balfred[0-9a-z._-]*\b"]),
    ("Intel", [r"\bneural-chat[0-9a-z._-]*\b"]),
    ("Open Orca", [r"\b(?:open-orca-platypus|orca-mini|mistral-openorca)[0-9a-z._-]*\b"]),
    ("Tencent", [r"\bllama-pro(?:model)?[0-9a-z._-]*\b"]),
    ("Phind", [r"\bphind[0-9a-z_-]\b"]),
    ("FlagAlpha", [r"\bllama2-chinese[0-9a-z_-]*\b"]),
    ("Liquid", [r"\blfm[0-9a-z._-]\b"]),
    ("Gradient", [r"\bgradient[0-9a-z_-]*\b"]),
    ("Groq", [r"\bgroq[0-9a-z_-]\b"]),
    ("George Sung", [r"\bllama2-uncensored[0-9a-z._-]*\b"]),
    ("Bespoke Labs", [r"\bbespoke[0-9a-z._-]\b"]),
    ("LG AI Research", [r"\bexaone[0-9a-z._-]\b"]),
    ("Essential AI", [r"\brnj-1[0-9a-z._-]*\b"]),
    ("Siraj Raval", [r"\bmedllama[0-9a-z._-]\b"]),
    ("MelodysDreamj", [r"\bwizard-vicuna(?!-uncensored)[0-9a-z._-]*\b"]),
    ("Cognitive Computations", [r"\b(?:dolphincoder|dolphin3|(?:mega|tiny)dolphin)[0-9a-z._-]*\b"]),
    ("Eric Hartford", [r"\b(?:dolphin-[0-9a-z._-]*|wizard-vicuna-uncensored|samantha-mistral[0-9a-z._-]*)\b"]),
    ("WizardLM", [r"\bwizardlm[0-9a-z._-]*\b"]),
    ("SentenceTransformers", [r"\ball[-\s]*minilm[0-9a-z._-]*\b"]),
    ("XTuner", [r"\bllava-phi[0-9a-z._-]\b"]),
    ("Microsoft", [r"\b(?:phi(?:[0-9][0-9a-z._-]*)?|orca(?!-mini)[0-9a-z._-]*|minilm)\b"]),
    ("Mistral", [r"\b(?:mistral|mixtral|codestral|mathstral|ministral|devstral|magistral)\b"]),
    ("Cohere", [r"\b(?:aya[0-9a-z._-]*|command[-\s]*(?:r7b|r|a))\b"]),
    ("NVIDIA", [r"\b(?:nemotron|chatqa[0-9a-z._-]*)\b"]),
    ("Stability AI", [r"\bstable[0-9a-z._-]*\b"]),
    ("Databricks", [r"\bdbrx\b"]),
    ("AllenAI", [r"\b(?:tulu|olmo)(?:[-\s]*\d)?\b"]),
    ("BlockMerge Gradient", [r"\b(?:blockmerge(?:\s+gradient)?|codebooga)\b"]),
    ("01.AI", [r"\byi\b"]),
    ("Nomic", [r"\bnomic\b"]),
    ("MotherDuck and Numbers Station", [r"\bduckdb\b"]),
    ("Snowflake", [r"\b(?:snowflake|arctic)\b"]),
    ("BAAI", [r"\bbge\b"]),
    ("Zhipu AI", [r"\bglm[0-9a-z._-]\b"]),
    ("Moonshot AI", [r"\bkimi\b"]),
    ("TII", [r"\bfalcon[0-9a-z_-]*\b"]),
    ("Hugging Face", [r"\bsmollm[0-9a-z._-]*\b"]),
    ("BigCode", [r"\bstarcoder[0-9a-z._-]*\b"]),
    ("mixedbread.ai", [r"\bmxbai\b"]),
    ("Banghua Zhu", [r"\bstarling[-\s]lm\b"]),
    ("InternLM", [r"\binternlm\b"]),
    ("LLaVA", [r"\bllava\b"]),
    ("Peiyuan Zhang", [r"\btinyllama[0-9a-z._-]*\b"]),
    ("Meta", [r"\b[0-9a-z._-]*llama[0-9a-z._-]*\b"]),
]

def infer_provider(text: str) -> str:
    for provider, patterns in PROVIDER_RULES:
        for pattern in patterns:
            if re.search(pattern, text, re.IGNORECASE):
                return provider

    return "Unknown"